services:
    event_store_client.event_store:
        class: EventStore\EventStore
        arguments:
            - '%event_store_client.base_url%'
        calls:
            - [setAuthorization, ['%event_store_client.user%', '%event_store_client.password%']]
