sudo: required

services:
  - docker

env:
  - SYMFONY_VERSION='2.8.*'
  - SYMFONY_VERSION='3.0.*'

before_install:
    - docker-compose up -d

install:
    - docker exec -it eventstoreclientbundle_php_1 bash -c "cd /var/www && composer require --no-update symfony/framework-bundle=${SYMFONY_VERSION}"
    - docker exec -it eventstoreclientbundle_php_1 bash -c "cd /var/www && composer install --prefer-dist --no-interaction"

script:
    - docker exec -it eventstoreclientbundle_php_1 bash -c "cd /var/www && bin/phpunit --coverage-clover=coverage.clover --coverage-text"
    - docker exec -it eventstoreclientbundle_php_1 bash -c "cd /var/www && bin/behat"

after_success:
  - docker exec -it eventstoreclientbundle_php_1 bash -c "cd /var/www && wget https://scrutinizer-ci.com/ocular.phar"
  - docker exec -it eventstoreclientbundle_php_1 bash -c "cd /var/www && php ocular.phar code-coverage:upload --format=php-clover coverage.clover"

after_scripts:
  - killall -SIGINT clusternode
